### ISSUE TITLE
error withmimetype application/x-www-form-urlencoded not 

### ISSUE THREAD

**Issue by fmurodov** [santiagobasulto/hyper-inspector#1]
Error with handle form data in POST:

```python
requests.post('http://localhost:5555/login', data={'username': 'user', 'password': 'secret',})
```

error:

```
127.0.0.1 - - [10/Apr/2021 19:24:59] "POST /login HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 56282)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/lib/python3.9/site-packages/http_inspector/handler.py", line 20, in do_X
    logger.log(request)
  File "/usr/lib/python3.9/site-packages/http_inspector/logger/rich_logger.py", line 97, in log
    pygments.lexers.get_lexer_for_mimetype(
  File "/usr/lib/python3.9/site-packages/pygments/lexers/__init__.py", line 226, in get_lexer_for_mimetype
    raise ClassNotFound('no lexer for mimetype %r found' % _mime)
pygments.util.ClassNotFound: no lexer for mimetype 'application/x-www-form-urlencoded' found

```

**Comment by santiagobasulto** [comment]
Thanks @firdavsich, just fixed it

**Comment by fmurodov** [comment]
Thank You!

> Thanks @firdavsich, just fixed it

Works. Thank you! It was fast)
